### ISSUE TITLE
Error in post_process

### ISSUE THREAD

**Issue by underbais** [abu-compbio/DriveWays#1]
Hello

I get this running on my own data:

DriveWays/src/strategy/Overlap.py", line 92, in post_process_modules
    avg_sizes.append(avg_size)
NameError: name 'avg_sizes' is not defined

Why would that be?

Thanks

**Comment by ilyes495** [comment]
Hey, sorry for the bug in the code, avg_sizes was supposed to be removed after refactoring the code. 
the code is fixed now and you shouldn't see this error again
